// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /home/federico/Documents/Universita/Federico_2020-2021/Aliwork/fastMCKalmanOptTesting/fastMCKalman/MC/fastSimulation.h;
#pragma link C++ defined_in "/home/federico/Documents/Universita/Federico_2020-2021/Aliwork/fastMCKalmanOptTesting/fastMCKalman/MC/fastSimulation.cxx";

#endif
